# Generated by Django 2.0.1 on 2018-01-26 04:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lightnings', '0002_catcher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catcher',
            new_name='Catch',
        ),
    ]
